import { Certificate } from '@/src/types/certificates';

const certificates: Certificate[] = [
  {
    id: '001',
    title: 'SEO para Iniciantes',
    educationalInstitution: 'Mirago',
    description: 'Um curso iniciante que me introduziu os fundamentos e conceitos básicos do SEO (Search Engine Optimization) pude aprender técnicas para melhorar o ranking do site no Google e aumentar o tráfego orgânico.',
    imageUrl: '',
    skills: ['Fundamentos de SEO', 'Planejamento Estratégico', 'Técnicas de Otimização', 'Pesquisa e Seleção de Palavras-chave', 'Análise Competitiva (Benchmarking)', 'Atração de Tráfego Qualificado'],
    certificateInfo: {
      imageUrl: '',
      docPDF: '',
      duration: '',
      date: '',
      level: 'Básico',
      technologies: []
    },
    goals: 'Entender como funciona o principal mecanismo de busca da atualidade: o Google.\nComo planejar o conteúdo do site com base nos conceitos de SEO.\nAplicar as boas práticas de SEO para atrair tráfego qualificado para o site!',
    projectUrl: '',
    repoUrl: '',
    activitiesDeveloped: ['Termos e conceitos relacionados ao SEO', 'Como funciona a indexação e o ranqueamento do Google', 'Entender quais as regras do jogo no universo do SEO', 'Entender as etapas num projeto de SEO', 'Como fazer uma pesquisa de palavras-chave na prática', 'Criar um planejamento de SEO', 'Criar um planejamento da estrutura de um site', 'Como fazer um benchmarking em SEO'],
    contentLearned: [],
  },
  {
    id: '002',
    title: 'Jornada Python da Hashtag',
    educationalInstitution: 'Hashtag Treinamentos',
    description: 'Um curso iniciante em que desenvolvi 4 projetos voltados a Análise de Dados, Automação, Criação de Sites e Inteligência Artificial. Com objetivo de aprimorar meus conhecimentos e habilidades em resolver desafios, automação de tarefas maçantes e a trabalhar com  dados.',
    imageUrl: '/img/certificates/JORNADA_PYTHON.jpg',
    skills: ['Automação de tarefas', 'Criação de gráficos e dashboards em Python', 'Treinamento e avaliação de modelos de ML'],
    certificateInfo: {
      imageUrl: '',
      docPDF: '',
      duration: '',
      date: '',
      level: 'Básico',
      technologies: []
    },
    goals: '',
    projectUrl: 'FALTA COLOCAR 4 PROJETOS',
    repoUrl: '',
    activitiesDeveloped: [],
    contentLearned: [],
  },
  {
    id: '003',
    title: 'Introdução à Análise de Dados - Microsoft Power BI',
    educationalInstitution: 'Fundação Bradesco',
    description: 'Neste curso introdutório pude aprender as principais atribuições de um analista de dados, suas habilidades, tarefas e processos com os quais trabalha.\n\nTive uma breve explanação teórica sobre a análise de dados com o uso do Microsoft Power BI para contar uma história convincente por meio de relatórios e painéis. Além da transformação de dados não relacionais em informações coerentes, visualmente imersivas e interativas.',
    imageUrl: '',
    skills: ['Análise de dados', 'Microsoft Power BI'],
    certificateInfo: {
      imageUrl: '',
      docPDF: '',
      duration: '',
      date: '',
      level: 'Básico',
      technologies: []
    },
    goals: '',
    projectUrl: '',
    repoUrl: '',
    activitiesDeveloped: [],
    contentLearned: [],
  },
  {
    id: '004',
    title: 'Formação Github Certification',
    educationalInstitution: 'DIO | Codifique o seu futuro',
    description: 'Uma formação completa sobre Git e GitHub no qual pude aprender sobre como aplicar práticas de desenvolvimento modernas, controle de versão para gerenciar projetos com eficiência, colaboração e administração de projetos e do ecossistema Git e GitHub.',
    imageUrl: 'img/certificates/FORMAÇÃO_GITHUB_CERTIFICATION.jpg',
    skills: { technical: ['Git', 'GitHub', 'GitHub Copilot', 'GitHub Codespaces'], technologies: ['github'], behavioral: [] },
    certificateInfo: {
      imageUrl: '',
      docPDF: '',
      duration: '',
      date: '',
      level: 'Básico',
      technologies: []
    },
    goals: '',
    projectUrl: '',
    repoUrl: '',
    activitiesDeveloped: ['Desafio de Código: Colocar em prática todo o conhecimento adquirido e testar o conhecimento na resolução de desafios.', 'Desafio de Projeto: Portfólio construído com meus projetos pessoais.'],
    contentLearned: [],
  },
  {
    id: '005',
    title: 'TypeScript na prática: implemente um projeto completo com TypeScript e módulos',
    educationalInstitution: 'Alura | Escola de Tecnologia Online',
    description: 'Curso de introdução aos fundamentos da linguagem Typescript em que foi desenvolvido uma aplicação para aprofundar e exemplificar estudos.\n\nA aplicação desenvolvida faz registro de transações em uma conta do Bytebank (Banco Fictício). Utilizando o formulário de novas transações, a pessoa usuária pode registrar transferências, fazer depósitos e fazer pagamentos de boleto.',
    imageUrl: '/img/certificates/TypeScript_na_prática_implemente_um_projeto_completo_com_TypeScript_e_módulos.jpg',
    skills: { technical: [], technologies: ['typescript', 'css3', 'JSX'], behavioral: [] },
    certificateInfo: {
      imageUrl: '',
      docPDF: '',
      duration: '',
      date: '',
      level: 'Básico',
      technologies: []
    },
    goals: '',
    projectUrl: '',
    repoUrl: '',
    activitiesDeveloped: [],
    contentLearned: ['Compreender os fundamentos e conceitos do TypeScript', 'Aprender a refatorar e melhorar o projeto usando TypeScript', 'Entender a configuração e compilação do código TypeScript', 'Explorar recursos como tipos primitivos, arrays, Type Alias e Enums', 'Organizar e dividir o projeto em módulos eficientes'],
  },
  {
    id: '006',
    title: 'TypeScript: aplicando orientação a objetos no Front-end',
    educationalInstitution: 'Alura | Escola de Tecnologia Online',
    description: 'Continuando o projeto do Bytebank (Banco Fictício). Este curso tem como foco a  aplicação e aprendizagem da orientação a objeto. No qual pude aprender sobre: Classes, Atributos, Métodos, Heranças e Decorators.',
    imageUrl: '/img/certificates/TypeScript_aplicando_orientação_a_objetos_no_Front-end.jpg',
    skills: { technical: ['Orientação a Objetos'], technologies: ['typescript'], behavioral: [] },
    certificateInfo: {
      imageUrl: '',
      docPDF: '',
      duration: '',
      date: '',
      level: 'Básico',
      technologies: []
    },
    goals: '',
    projectUrl: '',
    repoUrl: '',
    activitiesDeveloped: [],
    contentLearned: ['Compreender as características do paradigma funcional e de orientação a objetos com Typescript', 'Aprender a construir classes e métodos', 'Aprender como utilizar modificadores de acesso para melhorar a segurança do seu projeto', 'Aprender o conceito de herança para construir novas classes sem repetir código', 'Realizar a implementação de validações a partir de decorators'],
  },
  {
    id: '007',
    title: 'Contribuindo em um Projeto Open Source no GitHub',
    educationalInstitution: 'DIO | Codifique o seu futuro',
    description: 'Introdução ao fascinante universo da colaboração em código aberto. Projeto prático para treinar e desenvolver habilidades no trabalho colaborativo e da inovação contínua que o Open Source proporciona.',
    imageUrl: '/img/certificates/Contribuindo_em_um_Projeto_Open_Source.jpg',
    skills: { technical: ['Git', 'GitHub', 'Markdown'], technologies: [], behavioral: [] },
    certificateInfo: {
      imageUrl: '',
      docPDF: '',
      duration: '',
      date: '',
      level: 'Básico',
      technologies: []
    },
    goals: '',
    projectUrl: '',
    repoUrl: '',
    activitiesDeveloped: ['Formas de contribuir num Projeto Open Source', 'Desenvolvendo uma contribuição', 'Enviando uma contribuição'],
    contentLearned: [],
  },
  {
    id: '008',
    title: 'Princípios de Desenvolvimento de Software Colaborativo',
    educationalInstitution: 'DIO | Codifique o seu futuro',
    description: 'Curso focado nas práticas fundamentais de colaboração no desenvolvimento de software moderno. Abrange conceitos essenciais como controle de versão, fluxo de trabalho em equipe, revisão de código, integração contínua e documentação. O curso enfatiza boas práticas de colaboração entre desenvolvedores utilizando ferramentas amplamente adotadas no mercado.',
    imageUrl: '',
    skills: { technical: ['Git (branching, merge, rebase, logs, stash)', 'GitHub (pull requests, forks, issues, projetos, ações)', 'Integração Contínua e automação', 'Documentação técnica colaborativa', 'Organização de repositórios e versionamento semântico'], technologies: [], behavioral: ['Trabalho em equipe e comunicação técnica', 'Resolução de conflitos e tomada de decisão em grupo', 'Pensamento crítico e revisão de código', 'Organização, disciplina e gestão de tarefas', 'Colaboração assíncrona em ambientes remotos'] },
    certificateInfo: {
      imageUrl: '',
      docPDF: '',
      duration: '',
      date: '',
      level: 'Básico',
      technologies: []
    },
    goals: '',
    projectUrl: '',
    repoUrl: '',
    activitiesDeveloped: ['Trabalho com Git e GitHub para versionamento e colaboração em repositórios', 'Participação em code reviews e resolução de conflitos de merge', 'Criação e gerenciamento de branches e pull requests seguindo boas práticas', 'Implementação de workflows de CI/CD para automação de builds e testes', 'Escrita de documentação técnica colaborativa (READMEs, padrões, issues)', 'Desenvolvimento de projetos em equipe utilizando metodologias ágeis', 'Discussões técnicas e resolução de problemas via Issues e GitHub Projects'],
    contentLearned: [],
  },
  {
    id: '009',
    title: 'Angular: construa uma aplicação web com componentes, linguagem de template e CLI',
    educationalInstitution: 'Alura | Escola de Tecnologia Online',
    description: 'Curso introdutório que apresenta os fundamentos e como funciona o framework. Utilizando um modelo de site no Figma para construir o site Indexa, uma aplicação que lista e lida com contatos de uma agenda Introdução de como os componentes funcionam, pegar valores de inputs, evitar a repetição de código e a sintaxes de template para automatizar as tarefas do front-end.',
    imageUrl: '/img/certificates/Angular_construa_uma_aplicação_web_com_componentes_linguagem_de_template_e_CLI.jpg',
    skills: { technical: [], technologies: ['Typescript', 'CSS', 'Terminal (CLI)'], behavioral: [] },
    certificateInfo: {
      imageUrl: '',
      docPDF: '',
      duration: '',
      date: '',
      level: 'Básico',
      technologies: []
    },
    goals: 'Ter uma aplicação que lista todos os contatos vindo de um arquivo JSON, organizado por letras do alfabeto, tudo de forma automática. Buscar e filtrar por nome usando métodos do TypeScript de manipulação de string.',
    projectUrl: '',
    repoUrl: 'https://github.com/John-o-dev/indexa-Agenda-de-Contatos',
    activitiesDeveloped: [],
    contentLearned: ['Aprender a lidar com o terminal', 'geração de componentes', 'Escrever componentes reutilizáveis', 'Utilizar a linguagem de template do Angular para controlar o fluxo dos dados com @for', 'Explorar o uso do Angular CLI para criar aplicações e componentes', 'Ler arquivos JSON em Angular e ajustar configurações no arquivo tsconfig.json para atender às necessidades do seu projeto.'],
  },
  {
    id: '010',
    title: 'Angular: evoluindo com formulários e roteamento',
    educationalInstitution: 'Alura | Escola de Tecnologia Online',
    description: 'Curso de aprofundamento nos conceitos e funcionalidades do Angular, para isso, é utilizado o site do projeto\xa0Indexa - aplicação de agenda de contatos, e implementar o formulário para inserir novos contato.',
    imageUrl: '/img/certificates/Angular_evoluindo_com_formulários_e_roteamento.jpg',
    skills: { technical: ['Terminal (CLI)'], technologies: ['Angular', 'Typescript', 'CSS'], behavioral: [] },
    certificateInfo: {
      imageUrl: '',
      docPDF: '',
      duration: '',
      date: '',
      level: 'Básico',
      technologies: []
    },
    goals: 'Aprender como construir formulários reativos no Angular e como implementar validações dos campos utilizando as classes de validação do próprio Angular assim como configurar o roteamento da aplicação e navegar facilmente entre as telas.',
    projectUrl: '',
    repoUrl: 'https://github.com/John-o-dev/indexa-Agenda-de-Contatos',
    activitiesDeveloped: ['Construir Formulários Reativos utilizando FormGroup e FormControl', 'Implementar validações personalizadas nos campos do formulário com a classe Validators', 'Utilizar @if para renderizar mensagens de erro de forma condicional', 'Criar services e aplicar a injeção de dependências para modularizar e reutilizar o código', 'Estruturar o arquivo de rotas para uma navegação eficiente', 'Explorar o routerLink para facilitar redirecionamentos dentro da aplicação', 'Utilizar o serviço router e o método navigateByUrl para uma navegação programática eficaz'],
    contentLearned: ['Formulários Reativos (FormGroup e FormControl;)', 'Validators Angular', 'Services Angular', 'Navegação com routerLink, router e navigateByUrl'],
  },
  {
    id: '011',
    title: 'Angular: comunicando-se com uma API via requisições HTTP',
    educationalInstitution: 'Alura | Escola de Tecnologia Online',
    description:
      'Curso de aprofundamento nos conceitos e funcionalidades do Angular, usando um projeto já existente, o curso aborda conceitos e uso do HttpClient do Angular para fazer requisições do tipo HTTP, utilizando os métodos GET, POST, PUT, DELETE para enviar e obter dados do servidor. Como funcionam os observables (observáveis) e o que é necessário fazer para obter informações deles.',
    imageUrl: '/img/certificates/Angular_comunicandose_com_uma_API_via_requisições_HTTP.jpg',
    skills: { 
      technical: ['Typescript', 'HttpClient', 'CRUD', 'JSON Server', 'CSS', 'Terminal (CLI)'], 
      technologies: ['angular', 'typescript'],
      behavioral: ['Pensamento cógnitivo', 'Análise de dados'] },
    certificateInfo: {
      imageUrl: '/img/certificates/Angular_comunicandose_com_uma_API_via_requisições_HTTP.jpg',
      docPDF: '/pdf/certificates/Angular_comunicandose_com_uma_API_via_requisições_HTTP.pdf',
      duration: '6 horas',
      date: '2025-08-15',
      level: 'Básico',
      technologies: ['Angular', 'TypeScript', 'HTTP']
    },
    goals:
      'Aprender a utilizar o protocolo HTTP para integrar e comunicar a aplicação Angular a um back-end, utilizar boas práticas e fazer algumas melhorias no final do projeto, como a componentização e a reutilização de componentes em diferentes partes da aplicação.',
    projectUrl: 'https://project-angular-http-client.netlify.app/',
    repoUrl: 'https://github.com/repourl',
    activitiesDeveloped: ['Configurar o HttpClient para operações HTTP eficientes;', 'Implementar um CRUD usando métodos HTTP (GET, POST, PUT, DELETE);', 'User Observables para lidar com dados assíncronos;', 'Configurar e utilizar o JSON Server como uma API simulada;', 'Permitir a passagem de parâmetros na rota para facilitar a navegação;', 'Adaptar e integrar componentes para reutilização eficaz;', 'Promover boas práticas de componentização.'],
    contentLearned: ['Configuração', 'HttpClient'],
  },
];

export default certificates;