import Head from 'next/head';
import Link from 'next/link';

import useTranslation from '../hooks/useTranslation';

import Layout from '../components/Layout';
import HomePage from '../components/Home';
import HeaderMobile from '../components/HeaderMobile';
import Sidebar from '../components/Sidebar';
import Navbar from '../components/Navbar';
import About from '../components/About';
import Resume from '../components/Resume';
import Portfolio from '../components/Portfolio';

// import changeText from '../components/ChangeText';

export default function Home() {
  const { t, locale } = useTranslation();

  return (
    <>
      <Head>
        <title>John-o-dev</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>

        {/* {changeText()} */}
          
        <main>

          <HeaderMobile />

          <Sidebar />

          <div className="main-content">

            <Navbar />

            <HomePage />

            <About />

            <Resume />

            <Portfolio/>

            <article className="blog" data-page="blog">

              <header>
                <h2 className="h2 article-title">Blog</h2>
              </header>

              <div className="blog-bg">
                <p>
                  Em Breve...
                  Postagens sobre web design, programação e tecnologia.
                </p>
                <div className="gif-container">
                  <img src="img/dino.gif" alt="GIF animado" />
                </div>
              </div>
              
            </article>

          </div>
        </main>
      </div>

    </>

  );
}
